spring:
  datasource:
    url: jdbc:mysql://localhost/springfood?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create